# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "50395ad9c28ef355ed78152d48757081"
application_url = "https://announcement-bar-ruoa.onrender.com"
embedded = true
name = "Announcement Bar"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://announcement-bar-ruoa.onrender.com/api/auth",
  "https://announcement-bar-ruoa.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2026-07"

[build]
automatically_update_urls_on_dev = true
